// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCPQXDtb1gnlZQIf1bxAtLMtD07Dn7VhU',
    appId: '1:352406745700:web:b42c48d84fd26b5493e571',
    messagingSenderId: '352406745700',
    projectId: 'todo-firestore-7e4e2',
    authDomain: 'todo-firestore-7e4e2.firebaseapp.com',
    storageBucket: 'todo-firestore-7e4e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZzgVfSAYWKdz1jwYylFsDNXtcAJIk-w',
    appId: '1:352406745700:android:2b8552333b52011993e571',
    messagingSenderId: '352406745700',
    projectId: 'todo-firestore-7e4e2',
    storageBucket: 'todo-firestore-7e4e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFmrxbViaVdD0zVGJINQ3m_are0QQT2qg',
    appId: '1:352406745700:ios:8fe187c558b50dd993e571',
    messagingSenderId: '352406745700',
    projectId: 'todo-firestore-7e4e2',
    storageBucket: 'todo-firestore-7e4e2.appspot.com',
    iosClientId: '352406745700-bo5aa6s3u72qprlsj3urga372hdi2ufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFmrxbViaVdD0zVGJINQ3m_are0QQT2qg',
    appId: '1:352406745700:ios:8fe187c558b50dd993e571',
    messagingSenderId: '352406745700',
    projectId: 'todo-firestore-7e4e2',
    storageBucket: 'todo-firestore-7e4e2.appspot.com',
    iosClientId: '352406745700-bo5aa6s3u72qprlsj3urga372hdi2ufb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoApp',
  );
}
